apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanzubot1-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - tanzubot1.genaissance.ai
      secretName: tanzubot1-tls-secret
  rules:
    - host: tanzubot1.genaissance.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tanzubot1-service
                port:
                  number: 7860
